### PR TITLE
Charles/implement custom build workflow to (cross-)build rac in github workflow

### PR DESCRIPTION
**Pull request by charles2910**
Add steps to install build and cross-build dependencies, set up rust/cargo and build the package.

### CODE REVIEW

**Comment by leonheldattoradex** [comment]
Very clean and nice. Can we do something about the GitHub Actions warnings?
If not, let's close this and then work on it another time.

Also, can you add the attestation job?

**Comment by charles2910** [comment]
> Also, can you add the attestation job?

Yes, will do it.

> Can we do something about the GitHub Actions warnings?

Since we are using node from within the containers (requisite to use `action-rs/toolchain`), we are using a bit old stuff for Ubuntu 20.04 and Debian oldstable. I don't see an easy and clean way out of it as things are now.

The warning about upload using a deprecated version is easily solvable, I'll do it.

The one about `set-output` deprecation is happening on the `action-rs/toolchain`, and would need to be solved there.

Any preference if I should squash these fixes or commit them separately @leonheldattoradex?

**Comment by charles2910** [comment]
Updated as requested. I did squash the _small_ changes

**Review by leonheldattoradex — APPROVED** [review]
LGTM.

**Pull request merged**
